#!/bin/bash
# MediaHub Password Manager
# Securely stores, displays, and resets auto-generated passwords

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Password storage locations
CREDENTIALS_FILE="/opt/mediahub/.credentials"
CREDENTIALS_BACKUP="/mnt/media/backups/mediahub/.credentials.backup"
ENV_FILE="/opt/mediahub/.env"

generate_password() {
    local length=${1:-16}
    # Generate secure random password (alphanumeric + special chars)
    openssl rand -base64 32 | tr -d '/+=' | head -c "$length"
}

generate_simple_password() {
    local length=${1:-12}
    # Generate simple password (alphanumeric only, for services that don't support special chars)
    openssl rand -base64 32 | tr -d '/+=0OIl1' | head -c "$length"
}

encrypt_credentials() {
    local input_file="$1"
    local output_file="$2"
    local password="$3"

    openssl enc -aes-256-cbc -salt -pbkdf2 -in "$input_file" -out "$output_file" -pass pass:"$password" 2>/dev/null
}

decrypt_credentials() {
    local input_file="$1"
    local password="$2"

    openssl enc -aes-256-cbc -d -pbkdf2 -in "$input_file" -pass pass:"$password" 2>/dev/null
}

create_credentials_file() {
    local master_password="$1"

    echo -e "${BLUE}Generating secure passwords for all services...${NC}"

    # Generate passwords for each service
    local qbit_pass=$(generate_simple_password 12)
    local pihole_pass=$(generate_simple_password 12)
    local photoprism_pass=$(generate_password 16)
    local jellyfin_pass=$(generate_password 16)
    local prowlarr_api=$(generate_simple_password 32)
    local sonarr_api=$(generate_simple_password 32)
    local radarr_api=$(generate_simple_password 32)
    local lidarr_api=$(generate_simple_password 32)
    local code_server_pass=$(generate_password 16)

    # Create temporary plaintext credentials
    local temp_file=$(mktemp)

    cat > "$temp_file" << EOF
# MediaHub Credentials
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT SHARE THIS FILE!

=== WEB INTERFACE PASSWORDS ===

qBittorrent:
  URL: http://$(hostname -I | awk '{print $1}'):8080
  Username: admin
  Password: $qbit_pass

Pi-hole:
  URL: http://$(hostname -I | awk '{print $1}'):8053/admin
  Password: $pihole_pass

Photoprism:
  URL: http://$(hostname -I | awk '{print $1}'):2342
  Username: admin
  Password: $photoprism_pass

Jellyfin:
  URL: http://$(hostname -I | awk '{print $1}'):8096
  Username: (set during first login)
  Suggested Password: $jellyfin_pass

Code-Server (VSCode in browser):
  URL: http://$(hostname -I | awk '{print $1}'):8444
  Password: $code_server_pass

=== API KEYS (for service integration) ===

Prowlarr API Key: $prowlarr_api
Sonarr API Key: $sonarr_api
Radarr API Key: $radarr_api
Lidarr API Key: $lidarr_api

=== SERVICE URLs ===

Dashboard (Homarr): http://$(hostname -I | awk '{print $1}'):7575
Jellyfin: http://$(hostname -I | awk '{print $1}'):8096
Sonarr: http://$(hostname -I | awk '{print $1}'):8989
Radarr: http://$(hostname -I | awk '{print $1}'):7878
Lidarr: http://$(hostname -I | awk '{print $1}'):8686
Prowlarr: http://$(hostname -I | awk '{print $1}'):9696
Bazarr: http://$(hostname -I | awk '{print $1}'):6767
Code-Server: http://$(hostname -I | awk '{print $1}'):8444
Mylar3: http://$(hostname -I | awk '{print $1}'):8090
Komga: http://$(hostname -I | awk '{print $1}'):25600
Navidrome: http://$(hostname -I | awk '{print $1}'):4533
Jellyseerr: http://$(hostname -I | awk '{print $1}'):5055
Portainer: http://$(hostname -I | awk '{print $1}'):9000
Uptime Kuma: http://$(hostname -I | awk '{print $1}'):3001
Netdata: http://$(hostname -I | awk '{print $1}'):19999

=== NOTES ===

- First time setup required for: Jellyfin, Sonarr, Radarr, Lidarr, Prowlarr
- API keys above are suggestions - actual keys are generated by each service
- Change qBittorrent password immediately after first login
- ProtonVPN credentials are stored separately in .env file

EOF

    # Encrypt and save
    encrypt_credentials "$temp_file" "$CREDENTIALS_FILE" "$master_password"

    # Set secure permissions
    chmod 600 "$CREDENTIALS_FILE"

    # Backup to HDD (also encrypted)
    if [[ -d "/mnt/media/backups/mediahub" ]]; then
        cp "$CREDENTIALS_FILE" "$CREDENTIALS_BACKUP"
        chmod 600 "$CREDENTIALS_BACKUP"
    fi

    # Clean up
    shred -u "$temp_file" 2>/dev/null || rm -f "$temp_file"

    # Update .env with generated passwords
    update_env_passwords "$qbit_pass" "$pihole_pass" "$photoprism_pass" "$sonarr_api" "$radarr_api" "$lidarr_api" "$code_server_pass"

    echo -e "${GREEN}Credentials generated and encrypted${NC}"
}

update_env_passwords() {
    local qbit_pass="$1"
    local pihole_pass="$2"
    local photoprism_pass="$3"
    local sonarr_api="$4"
    local radarr_api="$5"
    local lidarr_api="$6"
    local code_server_pass="$7"

    if [[ -f "$ENV_FILE" ]]; then
        sed -i "s|^PIHOLE_PASSWORD=.*|PIHOLE_PASSWORD=$pihole_pass|" "$ENV_FILE"
        sed -i "s|^PHOTOPRISM_ADMIN_PASSWORD=.*|PHOTOPRISM_ADMIN_PASSWORD=$photoprism_pass|" "$ENV_FILE"
        sed -i "s|^SONARR_API_KEY=.*|SONARR_API_KEY=$sonarr_api|" "$ENV_FILE"
        sed -i "s|^RADARR_API_KEY=.*|RADARR_API_KEY=$radarr_api|" "$ENV_FILE"
        sed -i "s|^LIDARR_API_KEY=.*|LIDARR_API_KEY=$lidarr_api|" "$ENV_FILE"
        sed -i "s|^CODE_SERVER_PASSWORD=.*|CODE_SERVER_PASSWORD=$code_server_pass|" "$ENV_FILE"
    fi
}

show_credentials() {
    if [[ ! -f "$CREDENTIALS_FILE" ]]; then
        echo -e "${RED}No credentials file found.${NC}"
        echo "Run the installer first or use: $0 generate"
        exit 1
    fi

    echo -e "${YELLOW}Enter master password to view credentials:${NC}"
    read -sp "Master Password: " master_pass
    echo ""

    local decrypted=$(decrypt_credentials "$CREDENTIALS_FILE" "$master_pass" 2>&1)

    if [[ $? -ne 0 ]] || [[ -z "$decrypted" ]]; then
        echo -e "${RED}Invalid password or corrupted file${NC}"
        exit 1
    fi

    echo ""
    echo -e "${CYAN}=========================================${NC}"
    echo -e "${CYAN}  MediaHub Credentials${NC}"
    echo -e "${CYAN}=========================================${NC}"
    echo ""
    echo "$decrypted"
    echo ""
    echo -e "${YELLOW}Press any key to clear screen...${NC}"
    read -n 1 -s
    clear
    echo -e "${GREEN}Credentials cleared from screen${NC}"
}

export_credentials() {
    if [[ ! -f "$CREDENTIALS_FILE" ]]; then
        echo -e "${RED}No credentials file found.${NC}"
        exit 1
    fi

    local output_file="${1:-/tmp/mediahub-credentials.txt}"

    echo -e "${YELLOW}Enter master password:${NC}"
    read -sp "Master Password: " master_pass
    echo ""

    local decrypted=$(decrypt_credentials "$CREDENTIALS_FILE" "$master_pass" 2>&1)

    if [[ $? -ne 0 ]]; then
        echo -e "${RED}Invalid password${NC}"
        exit 1
    fi

    echo "$decrypted" > "$output_file"
    chmod 600 "$output_file"

    echo -e "${GREEN}Credentials exported to: $output_file${NC}"
    echo -e "${YELLOW}WARNING: This file is NOT encrypted. Delete after use!${NC}"
}

reset_password() {
    local service="$1"

    if [[ -z "$service" ]]; then
        echo "Available services to reset:"
        echo "  qbittorrent"
        echo "  pihole"
        echo "  photoprism"
        echo "  all (regenerate everything)"
        echo ""
        read -p "Service to reset: " service
    fi

    echo -e "${YELLOW}Enter master password:${NC}"
    read -sp "Master Password: " master_pass
    echo ""

    case "$service" in
        qbittorrent)
            local new_pass=$(generate_simple_password 12)
            echo -e "${GREEN}New qBittorrent password: $new_pass${NC}"
            echo ""
            echo "To apply:"
            echo "  1. Open qBittorrent web UI"
            echo "  2. Go to Options > Web UI"
            echo "  3. Change password to: $new_pass"
            ;;
        pihole)
            local new_pass=$(generate_simple_password 12)
            echo -e "${GREEN}New Pi-hole password: $new_pass${NC}"
            sed -i "s|^PIHOLE_PASSWORD=.*|PIHOLE_PASSWORD=$new_pass|" "$ENV_FILE"
            echo "Restarting Pi-hole..."
            docker restart pihole 2>/dev/null || true
            ;;
        photoprism)
            local new_pass=$(generate_password 16)
            echo -e "${GREEN}New Photoprism password: $new_pass${NC}"
            sed -i "s|^PHOTOPRISM_ADMIN_PASSWORD=.*|PHOTOPRISM_ADMIN_PASSWORD=$new_pass|" "$ENV_FILE"
            echo "Restarting Photoprism..."
            docker restart photoprism 2>/dev/null || true
            ;;
        all)
            echo "Regenerating all passwords..."
            create_credentials_file "$master_pass"
            echo -e "${GREEN}All passwords regenerated${NC}"
            echo "Restart services to apply: ./stop.sh && ./start.sh"
            ;;
        *)
            echo -e "${RED}Unknown service: $service${NC}"
            exit 1
            ;;
    esac
}

change_master_password() {
    if [[ ! -f "$CREDENTIALS_FILE" ]]; then
        echo -e "${RED}No credentials file found.${NC}"
        exit 1
    fi

    echo -e "${YELLOW}Enter current master password:${NC}"
    read -sp "Current Password: " old_pass
    echo ""

    # Verify old password
    local decrypted=$(decrypt_credentials "$CREDENTIALS_FILE" "$old_pass" 2>&1)
    if [[ $? -ne 0 ]]; then
        echo -e "${RED}Invalid current password${NC}"
        exit 1
    fi

    echo -e "${YELLOW}Enter new master password:${NC}"
    read -sp "New Password: " new_pass
    echo ""
    read -sp "Confirm New Password: " confirm_pass
    echo ""

    if [[ "$new_pass" != "$confirm_pass" ]]; then
        echo -e "${RED}Passwords do not match${NC}"
        exit 1
    fi

    # Re-encrypt with new password
    local temp_file=$(mktemp)
    echo "$decrypted" > "$temp_file"
    encrypt_credentials "$temp_file" "$CREDENTIALS_FILE" "$new_pass"
    shred -u "$temp_file" 2>/dev/null || rm -f "$temp_file"

    # Update backup
    if [[ -d "/mnt/media/backups/mediahub" ]]; then
        cp "$CREDENTIALS_FILE" "$CREDENTIALS_BACKUP"
    fi

    echo -e "${GREEN}Master password changed successfully${NC}"
}

show_help() {
    echo "MediaHub Password Manager"
    echo ""
    echo "Usage: $0 <command> [options]"
    echo ""
    echo "Commands:"
    echo "  generate              Generate new passwords for all services"
    echo "  show                  Display all stored credentials"
    echo "  export [file]         Export credentials to plaintext file"
    echo "  reset <service>       Reset password for specific service"
    echo "  change-master         Change the master password"
    echo "  help                  Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 show                    # View all passwords"
    echo "  $0 reset qbittorrent      # Reset qBittorrent password"
    echo "  $0 export ~/passwords.txt  # Export to file"
    echo ""
}

main() {
    local command="${1:-help}"

    case "$command" in
        generate)
            echo -e "${YELLOW}Create a master password to encrypt all credentials.${NC}"
            echo "This password will be needed to view or manage credentials later."
            echo ""
            read -sp "Enter Master Password: " master_pass
            echo ""
            read -sp "Confirm Master Password: " confirm_pass
            echo ""

            if [[ "$master_pass" != "$confirm_pass" ]]; then
                echo -e "${RED}Passwords do not match${NC}"
                exit 1
            fi

            if [[ ${#master_pass} -lt 8 ]]; then
                echo -e "${RED}Master password must be at least 8 characters${NC}"
                exit 1
            fi

            create_credentials_file "$master_pass"
            ;;
        show)
            show_credentials
            ;;
        export)
            export_credentials "$2"
            ;;
        reset)
            reset_password "$2"
            ;;
        change-master)
            change_master_password
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            echo -e "${RED}Unknown command: $command${NC}"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
